-- MySQL Script generated by MySQL Workbench
-- Qua 25 Out 2017 10:56:57 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema riso-web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema riso-web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `riso-web` DEFAULT CHARACTER SET utf8 ;
USE `riso-web` ;

-- -----------------------------------------------------
-- Table `riso-web`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `riso-web`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(256) NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `nivel` INT NOT NULL DEFAULT 1,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `criado_por` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_usuarios_usuarios_idx` (`criado_por` ASC),
  CONSTRAINT `fk_usuarios_usuarios`
    FOREIGN KEY (`criado_por`)
    REFERENCES `riso-web`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
